#!/bin/sh

# Get path of repo directory (the one containing this script)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Setup tmux
ln -s -f $DIR/tmux/.tmux.conf ~
ln -s -f $DIR/tmux/.tmux.conf.local ~

# Setup Micro
rm -r ~/.config/micro
ln -s $DIR/micro ~/.config

# Default editorconfig (for any files below users home)
ln -s -f $DIR/.editorconfig ~
