#!/bin/bash

# Update submodules
git submodule update --init --recursive

# Get path of repo directory (the one containing this script)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Setup tmux
ln -s -f $DIR/tmux/.tmux.conf ~
ln -s -f $DIR/tmux/.tmux.conf.local ~
TMUXX='alias tmuxx="tmux new-session -A -s"'
grep -q "$TMUXX" ~/.bashrc || echo "$TMUXX" >> ~/.bashrc

# Setup neovim
mkdir -p ~/.config/nvim
ln -s -f $DIR/neovim/init.vim ~/.config/nvim/
DEIN_DIR=~/.local/share/nvim/dein/repos/github.com/Shougo
rm -rf $DEIN_DIR/dein.vim || true
mkdir -p $DEIN_DIR
ln -s $DIR/neovim/dein.vim $DEIN_DIR
echo "To get neovim up and running open it and run :call dein#install()"

# Setup zsh
./zsh/zsh_install.py

# Fonts
mkdir -p ~/.fonts
rm -rf ~/.fonts/nerd-fonts || true
ln -s $DIR/fonts/nerd-fonts ~/.fonts/

# Setup Micro
rm -rf ~/.config/micro || true
ln -s $DIR/micro ~/.config

# Default editorconfig (for any files below users home)
ln -s -f $DIR/.editorconfig ~
