POWERLEVEL9K_INSTALLATION_PATH=$HOME/.zsh/themes/powerlevel9k
POWERLEVEL9K_MODE='nerdfont-fontconfig'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir dir_writable virtualenv vcs status newline vi_mode)
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=""
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# OS Icon
POWERLEVEL9K_OS_ICON_BACKGROUND="253"
if [[ $DISTRO == "Ubuntu" ]]; then
    POWERLEVEL9K_OS_ICON_FOREGROUND="009"
else
    POWERLEVEL9K_OS_ICON_FOREGROUND="004"
fi

# Path
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="037"  # Adapta
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="255"  # White
POWERLEVEL9K_DIR_HOME_BACKGROUND="037"
POWERLEVEL9K_DIR_HOME_FOREGROUND="255"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="037"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="255"
POWERLEVEL9K_DIR_ETC_BACKGROUND="037"
POWERLEVEL9K_DIR_ETC_FOREGROUND="255"

# Python
POWERLEVEL9K_VIRTUALENV_FOREGROUND="255"

# Version Control
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="255"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="255"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="255"
POWERLEVEL9K_VCS_SHORTEN_LENGTH=20
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=20
POWERLEVEL9K_VCS_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_VCS_SHORTEN_DELIMITER=".."
POWERLEVEL9K_STATUS_OK_BACKGROUND="236"

# VI Mode
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND="037"
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND="255"
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND="037"
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND="255"
POWERLEVEL9K_VI_COMMAND_MODE_STRING=":"
POWERLEVEL9K_VI_INSERT_MODE_STRING="%%"

